#!/usr/bin/env bash
#
# Chorion setup — creates the distrobox environment and installs dependencies.
#
# Run once:   bash src/chorion/setup.sh
# Then start: bash src/chorion/start.sh
#
set -euo pipefail

DISTROBOX_NAME="chorion"
DISTROBOX_IMAGE="fedora:42"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.chorion"

echo "=== Chorion Setup ==="
echo "Project root: $PROJECT_ROOT"
echo ""

# --- 1. Create .env.chorion first (so start.sh works even if deps fail) ---
if [ ! -f "$ENV_FILE" ]; then
    echo "[..] Creating $ENV_FILE..."

    SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")

    cat > "$ENV_FILE" << EOF
# Chorion environment configuration
# Generated by setup.sh — edit as needed

# Service-to-service authentication secret
# This MUST match CHORION_SERVICE_SECRET in HatChat's .env
CHORION_SERVICE_SECRET=$SECRET

# MongoDB connection (default: HatChat's MongoDB via docker-compose)
MONGO_URI=mongodb://localhost:27017

# Database name (shares HatChat's database, uses chorion_* prefixed collections)
CHORION_DB_NAME=LibreChat

# Bind address and port
CHORION_HOST=127.0.0.1
CHORION_PORT=8901
EOF

    echo "[ok] Created $ENV_FILE"
    echo ""
    echo "  IMPORTANT: Add this to your HatChat .env file:"
    echo "    CHORION_SERVICE_SECRET=$SECRET"
    echo "    CHORION_BASE_URL=http://127.0.0.1:8901"
    echo ""
else
    echo "[ok] $ENV_FILE already exists"
fi

# --- 2. Create distrobox if it doesn't exist ---
if distrobox list 2>/dev/null | grep -q "$DISTROBOX_NAME"; then
    echo "[ok] Distrobox '$DISTROBOX_NAME' already exists"
else
    echo "[..] Creating distrobox '$DISTROBOX_NAME' ($DISTROBOX_IMAGE)..."
    distrobox create \
        --name "$DISTROBOX_NAME" \
        --image "$DISTROBOX_IMAGE" \
        --nvidia \
        --yes
    echo "[ok] Distrobox created"
fi

# --- 3. Install Python deps inside distrobox ---
echo ""
echo "[..] Installing dependencies inside distrobox..."
distrobox enter "$DISTROBOX_NAME" -- bash -c "
    set -euo pipefail

    # Ensure pip is available
    if ! command -v pip3 &>/dev/null; then
        echo '  Installing pip...'
        sudo dnf install -y python3-pip
    fi

    # Ensure build tools for native extensions
    if ! command -v gcc &>/dev/null; then
        echo '  Installing build tools...'
        sudo dnf install -y gcc gcc-c++ python3-devel
    fi

    # Ensure poetry
    if ! command -v poetry &>/dev/null; then
        echo '  Installing poetry...'
        pip3 install --user poetry
    fi
    echo '  poetry: '\$(poetry --version)
    echo '  python: '\$(python3 --version)

    # Install project deps
    cd '$PROJECT_ROOT'

    # Re-lock if the existing lock file has incompatible pins
    # (e.g. generated on Python 3.14 host, now running 3.13 in distrobox)
    if [ -f poetry.lock ]; then
        echo '  Removing stale poetry.lock (will re-resolve for this Python)...'
        rm -f poetry.lock
    fi

    echo '  Resolving dependencies (this may take a few minutes)...'
    poetry lock --no-interaction 2>&1 | tail -5

    echo '  Installing...'
    poetry install --no-interaction 2>&1 | tail -10

    echo '  Done.'
"
echo "[ok] Dependencies installed"

echo ""
echo "=== Setup complete ==="
echo ""
echo "To start Chorion:"
echo "  bash src/chorion/start.sh"
echo ""
echo "To start in dev mode (auto-reload):"
echo "  bash src/chorion/start.sh --reload"
